// MARK: - Embedded Cat Names Data (Production)
let embeddedCatNames: [String] = [
    "A Cappella",
    "A Cat",
    "A Net (aka Nettie)",
    "A'ja (pronounced \"Asia\")",
    "A.C. (Alternating Current)",
    "A.C. (Another Cat)",
    "A.C. (Attack Cat)",
    "A.C. (Attitude Cat)",
    "A.D.D. (Attention Deficit Disorder)",
    "A.J. (Angelina Jolie)",
    "A.J. (Angelo Jo)",
    "A.L.F. (Alien Life Form)",
    "A.V.P. (Alien vs Predator)",
    "Aaargh",
    "Aaliyah",
    "Aaron",
    "Ab",
    "Ababa",
    "Abba",
    "Abba-daba",
    "Abba-Goo",
    "Abbey",
    "Abbey Roads",
    "Abbi-girl",
    "Abbie",
    "Abbot",
    "Abbott",
    "Abby",
    "Abby-girl",
    "Abby-normal",
    "Abbykitty",
    "Abcat",
    "Abdul",
    "Abe",
    "Abednego",
    "Abegale",
    "Abel",
    "Abelard",
    "Abendigo",
    "Abercrombie",
    "Aberdeen",
    "Abi",
    "Abigail",
    "Abigail Von Buttons",
    "Abilene",
    "Able",
    "Abner",
    "Abra",
    "Abra (and Cadabra?)",
    "Abracadabra",
    "Abraham",
    "Abraxas",
    "Abrico",
    "Abs",
    "Absinthe",
    "Absolon (from Chaucer's \"Cabterbury Tales\")",
    "Absolut (named after the Swedish vodka)",
    "Abstraction",
    "Abu",
    "Abubu",
    "Aby",
    "Abyss",
    "Acat",
    "Ace",
    "Ace Baby Toadflakes",
    "Ace Of Spades",
    "Acey",
    "Achille",
    "Achilles (Greek mythology: Champion of the Greeks in the Trojan War)",
    "Acis",
    "Ackerly",
    "Acorn",
    "Acrolina",
    "Acroy",
    "Action",
    "Ada",
    "Ada Jane",
    "Adacat",
    "Adagio",
    "Adakin Skywalker",
    "Adam",
    "Adam And Eve",
    "Adams",
    "Adcom",
    "Addie",
    "Addis",
    "Addison",
    "Addy",
    "Addy-Tood",
    "Adelaida",
    "Adelaide",
    "Ademma",
    "Adidas",
    "Adirondak",
    "Adiza",
    "Adlai",
    "Adler",
    "Admetus",
    "Admiral",
    "Adobe",
    "Adolph",
    "Adom",
    "Adonis",
    "Adrian",
    "Adriatic",
    "Adrock",
    "Advance Cat",
    "Aegyptos",
    "Aelgifa (The Elven Gift - Old English)",
    "Aelurus (Egyptian mythology, sacred cat)",
    "Aenias",
    "Aeolus (Greek God of the Wind)",
    "Aerope",
    "Aeros",
    "Aesop",
    "Aethelwyn",
    "Aethra",
    "Affinity",
    "Afikoman",
    "Afonia",
    "Africa",
    "African Queen",
    "African-Americat",
    "Afrikan",
    "Afrikat",
    "Agadore",
    "Agamemnon",
    "Agape (from the New Testament meaning unconditional love)",
    "Agassi",
    "Agatha",
    "Agatha Christie",
    "Agatha Christy",
    "Agent Z",
    "Aggedor",
    "Aggie",
    "Agili-tree",
    "Agility",
    "Agima",
    "Agitador (Spanish for \"troublemaker\")",
    "Agnes",
    "Agrippina",
    "Agustus",
    "Ah Kinchil (Maya mythology: the sun god)",
    "Ah Puch (Maya mythology: the god of death)",
    "Ah-choo!",
    "Ahab",
    "Ahau Chamahez (Maya mythology: one of two gods of medicine)",
    "Ahi",
    "Ahlia",
    "Ahmakiq (Maya mythology: god of agriculture)",
    "Ahura Mazda",
    "Aida",
    "Aidan",
    "Aiiy",
    "Aikido",
    "Aiko",
    "Aimee",
    "Air",
    "Air Einstein",
    "Air Raid",
    "Airhead",
    "AJ",
    "Aja",
    "Ajah (priesthood in fantasy games)",
    "Ajax",
    "Akaia",
    "Akamai (Hawaiian for \"smart\")",
    "Akasha",
    "Akasha (character in Anne Rice's vampire chronicles)",
    "Akasha (Queen Mother Vampire from Anne Rice's \"Queen of the Damned\")",
    "Akbar",
    "Akeel",
    "Akeel The One Eyed",
    "Akeela",
    "Akeem",
    "Akeisha",
    "Aker (Egyptian mythology: the lion who guards the gates of dawn)",
    "Akhen",
    "Akhushtal (Maya mythology: goddess of childbirth)",
    "Aki",
    "Akim",
    "Akira",
    "Akita (Japanese breed of dog)",
    "Aktil (after the mouse in \"Aktil's Big Swim\" children's book by Inga Moore)",
    "Aku",
    "Akula",
    "Akuna",
    "Al",
    "Al Bundy",
    "Al Capone",
    "Al Pacino (after the actor)",
    "Alabama",
    "Alabaster",
    "Aladara",
    "Aladdin",
    "Alakazam!",
    "Alan",
    "Alani",
    "Alanna",
    "Alaska",
    "Alastair",
    "Albatross",
    "Albee (after the playwright Edward Albee)",
    "Albert",
    "Albert Einstein",
    "Albert Oscelish Loudpurr",
    "Alberta",
    "Alberto",
    "Albie-Capone",
    "Albrecht",
    "Alcatraz",
    "Alchemy",
    "Alcuin",
    "Aldebaran",
    "Aldo",
    "Aldo Scalicki",
    "Aldous (after the British author, Aldous Huxley)",
    "Alecia",
    "Alegra",
    "Alegria Noah",
    "Aleister",
    "Aleksandra",
    "Aleksei",
    "Aleta",
    "Alex",
    "Alex P. Kitten",
    "Alexa",
    "Alexander",
    "Alexander Blitzen Cody",
    "Alexander Blue",
    "Alexander-The-Great",
    "Alexandra",
    "Alexandra The Great",
    "Alexandra The Grey",
    "Alexandria",
    "Alexandroupolis",
    "Alexia",
    "Alexis",
    "Alf",
    "Alfa Skywalker",
    "Alfalfa",
    "Alfanzo",
    "Alfie",
    "Alfie Moon (after the character in the \"Eastenders\" tv-series)",
    "Alfiepet",
    "Alfonzo",
    "Alfred",
    "Alfred \"Lord\" Tennyson",
    "Alfreda",
    "Algebra",
    "Alger",
    "Algernon",
    "Algy",
    "Ali",
    "Ali Baba",
    "Ali Kat",
    "Ali Khat",
    "Alia",
    "Alibi",
    "Alice",
    "Alice B. Toe-Claws",
    "Alice B. Toklas",
    "Alien",
    "Alika",
    "Aliki",
    "Alimony",
    "Alina",
    "Alise",
    "Alistair",
    "Alistair Jones",
    "Alix",
    "Aliza",
    "Alize",
    "All This and Heaven Too",
    "Alla",
    "Alladin",
    "Allan",
    "Allball",
    "Allegra",
    "Allegro",
    "Allergen",
    "Alley",
    "Alley McClaw",
    "Allie",
    "Allie Cat",
    "Allie Marie",
    "Allison",
    "Allison Jo",
    "Allred",
    "Allspice",
    "Allura",
    "Ally",
    "Alma (Spanish for soul)",
    "Almanzo",
    "Almond Roca",
    "Almost Paradise (song \"Almost Paradise\")",
    "Aloha",
    "Aloka",
    "Alokee",
    "Alomar",
    "Alonzo",
    "Alouiscious",
    "Alowicious",
    "Aloysius",
    "Alpaca",
    "Alpha",
    "Alphie",
    "Alpine",
    "Alsatia",
    "Althea",
    "Alton",
    "Aluminum",
    "Alvin",
    "Alwix",
    "Alyssa",
    "Alyx",
    "Am-fats",
    "Ama",
    "Amable",
    "Amadaeus",
    "Amadala",
    "Amadeus",
    "Amadeus (after Mozart)",
    "Amalthea",
    "Amanda",
    "Amandalina",
    "Amanita",
    "Amaretto",
    "Amazing Grace",
    "Amazon",
    "Amba",
    "Ambar",
    "Ambassador",
    "Amber",
    "Amberwavesoffur",
    "Ambidextrous",
    "Ambiguity",
    "Ambiguous Eunuch FarFromScrewin",
    "Amble",
    "Ambriel (Zodiac, guardian angel of Gemini)",
    "Ambrose",
    "Ambrose Ambrogo",
    "Ambrose Bugger-Boo Pendragon",
    "Ambrosia",
    "Ambrosia Jean Marie",
    "Ambrosious",
    "Ambush",
    "Amby",
    "Amby (one of the feminine forms of Ambrose)",
    "Amelia",
    "Amelia Air-Cat",
    "Amelia Earhart",
    "Amelie (after the movie)",
    "Amen-Ra",
    "Amenhotep",
    "America",
    "American Pie",
    "Americat",
    "Amerito",
    "Amethyst",
    "Ami",
    "Amida",
    "Amidala",
    "Amie",
    "Amiga",
    "Amigo",
    "Amir",
    "Amira (Female Arabian name, meaning \"princess\")",
    "Ammie",
    "Ammo",
    "Amon",
    "Amor (Spanish for \"love\")",
    "Amore",
    "Amos",
    "Amour (French for \"love\")",
    "Ampersand",
    "Amphion",
    "Amsterdam",
    "Amtrak",
    "Amulet",
    "Amway",
    "Amy",
    "Amy Budd",
    "Amydala",
    "Ana",
    "Ana-Hata",
    "Anaakii (Japanese for \"anarchy\")",
    "Anabel",
    "Anabell",
    "Anabelle",
    "Anacharsis",
    "Anaconda",
    "Anais",
    "Anakin",
    "Anamokit (Indian for \"Little Thunder\")",
    "Anastasia",
    "Anastasia (after the Russian princess)",
    "Anatevka",
    "Anatole",
    "Anatolius",
    "Anatoly",
    "Anchor",
    "Anchors Away",
    "Anchovey",
    "Anchovy",
    "Ancona",
    "Andaconda",
    "Andalusia",
    "Anderson",
    "Andi",
    "Andie",
    "Andilay, Andilay!",
    "Andorra",
    "Andouille (after the spicy Cajun sausage)",
    "Andre",
    "Andrea",
    "Andrea Majorie",
    "Andreas",
    "Andrew",
    "Andrew Elliott James David",
    "Andrew Jackson",
    "Android",
    "Andromeda",
    "Andy",
    "Andy Rooney",
    "Anfurnee",
    "Angel",
    "Angel Boy",
    "Angel Cookie",
    "Angel Eyes",
    "Angel Marie",
    "Angela",
    "Angelee",
    "Angelface",
    "Angelica",
    "Angelika",
    "Angelika (after Angelika Foster-Gooding)",
    "Angelina",
    "Angeline",
    "Angelo",
    "Angelo Jo",
    "Angie",
    "Angstrom",
    "Angus",
    "Angus MacDoogal",
    "Angus MacGuyver",
    "Angus Pangus",
    "Angus Suzy-Socks",
    "Angy Poo",
    "Ani",
    "Ani Difranco",
    "Anika",
    "Anikki",
    "Animal",
    "Animophat",
    "Anina",
    "Anishka",
    "Anita Blake (after the Laurel K. Hamilton novels)",
    "Anitra",
    "Ankelfraeseren",
    "Ankle Biter",
    "Ankle Dancer",
    "Ann",
    "Ann Jelly",
    "Ann-Margaret",
    "Anna",
    "Anna-lynn",
    "Annabel",
    "Annabelle",
    "Annakin (after Annakin Skywalker in the Star Wars movies)",
    "Annapolis",
    "Annapurna",
    "Annelee",
    "Annette",
    "Annible",
    "Annie",
    "Annie Banannie",
    "Annie Marie",
    "Annie Pearl",
    "Anniey",
    "Anonka",
    "Anonymous",
    "Anouk (after Anouk Aimee)",
    "Anouk Manouk",
    "Anowa",
    "Ansel",
    "Ansel Adams",
    "Ansel Catams",
    "Antar (after a character in Arabic literature known for his bravery)",
    "Antarctica",
    "Antares",
    "Antelope",
    "Antha",
    "Anthea",
    "Anthem",
    "Anthony",
    "Anthrax P.H. (Poo Head) Zeppelin",
    "Antic",
    "Antigone",
    "Anton",
    "Anton B. Stanton",
    "Antonia",
    "Antonio",
    "Antonio Banderas",
    "Antony",
    "Antony And Cleopatra",
    "Antos",
    "Antryg",
    "Anubis",
    "Anxiety",
    "Anya",
    "Apache",
    "Aphrodisia",
    "Aphrodite",
    "Aphrodite, The Kitten Of Love",
    "Apie",
    "Apocalypse",
    "Apocalypse Now",
    "Apogee",
    "Apollo",
    "Apollo (the mythological god of light and truth)",
    "Apollonia",
    "Apothecary",
    "Applaton",
    "Apple",
    "Apple Dog",
    "Apple Pie",
    "Applejack",
    "Applesauce",
    "Appleton",
    "Appollinia",
    "Apprentice",
    "Appy",
    "Apri",
    "Apricot",
    "April",
    "Aptos",
    "Apu",
    "Aput",
    "Apuu",
    "Aqua",
    "Aqua Girl",
    "Aquarius",
    "Ar-too",
    "Arachne",
    "Aragorn",
    "Araine",
    "Aramer",
    "Aramis (one of the three muskateers)",
    "Arapaho",
    "Arbitration",
    "Arbuckle (after the silent film comedian)",
    "Arbutis",
    "Arby",
    "Archibald",
    "Archie",
    "Archie Bunker",
    "Archima",
    "Archimedes",
    "Ardal",
    "Area 51",
    "Arejay Joseph (Arejay from the band Halestorm)",
    "Arendal",
    "Ares",
    "Arf",
    "Arfie",
    "Arfur",
    "Argent",
    "Argo",
    "Argon",
    "Argos",
    "Argus",
    "Argyle",
    "Ari",
    "Aria",
    "Ariadne (Greek mythology, daughter of King Minos of Crete)",
    "Ariel",
    "Ariel (from the movie \"The Little Mermaid\")",
    "Ariela (Hebrew for \"female derivative of lioness\")",
    "Arielle",
    "Aries",
    "Arietty",
    "Arioch",
    "Arista Kat",
    "AristoCat",
    "Aristophanes",
    "Aristotle",
    "Arizona",
    "Arlene",
    "Arlington",
    "Arlo",
    "Arly",
    "Armageddon",
    "Armani",
    "Armie",
    "Arms",
    "Arms Von Hirshstein",
    "Armstrong",
    "Arnie",
    "Arnold",
    "Arnold Schwarzenegger",
    "Arnold Shortzenlegger",
    "Arpeggio",
    "Arquette",
    "Arriana",
    "Arrow",
    "Arsenic",
    "Artemis",
    "Artemis (Greek goddess of hunting and moon)",
    "Artera",
    "Artesian",
    "Artful Dodger",
    "Arthur",
    "Arthur Ambrosius",
    "Arti",
    "Artie",
    "Arty",
    "Arvo",
    "Arwen",
    "Arwen Renaissance",
    "Arzu (Turkish for \"desire\")",
    "Asbury (after Asbury Park, NJ)",
    "ASCII (computer term)",
    "Ash",
    "Ash-butt",
    "Asha",
    "Ashanti",
    "Ashben",
    "Asheema",
    "Asher",
    "Ashes",
    "Ashes Too Ashes",
    "Ashford",
    "Ashika",
    "Ashke",
    "Ashleigh",
    "Ashley",
    "Ashley Cat",
    "Ashley Olsen",
    "Ashley Wilkes",
    "Ashli",
    "Ashlyn",
    "Ashrei (Hebrew for \"happy\")",
    "Ashton",
    "Ashur",
    "Asia",
    "Asia Major",
    "Asia Minor",
    "Asimov",
    "Asja",
    "Aska",
    "Asker",
    "Askhim",
    "Aslan",
    "Asparagus",
    "Aspen",
    "Asphalt",
    "Aspirin",
    "Asscaught",
    "Asset",
    "Asta",
    "Astarael",
    "Astarte",
    "Aster",
    "Asterix",
    "Asteroid",
    "Asti",
    "Asti Spumonte",
    "Astor",
    "Astra",
    "Astro",
    "Astroid",
    "Astrology",
    "Astroman",
    "Astrophe",
    "Asylum",
    "Asymptote",
    "Atair",
    "Atari",
    "Ateesha",
    "Athalia",
    "Athena (Goddess of War)",
    "Athene",
    "Athens",
    "Athinai",
    "Atilla",
    "Atinna",
    "Atlantic",
    "Atlantis",
    "Atlas",
    "Atom",
    "Atossa",
    "Attacker",
    "Atte",
    "Atti (short for attitude)",
    "Atticus",
    "Attila",
    "Attitude",
    "Atude",
    "Aubergine",
    "Aubrey",
    "Audacity",
    "Audball",
    "Auden (named after the poet W.H. Auden)",
    "Audie",
    "Audio",
    "Auditor",
    "Audrey",
    "Audrey Hepburn",
    "Audrey III",
    "Audubon (after John James Audubon)",
    "Augger-Dogger",
    "Auggie",
    "Auggie Doggie",
    "Auggie or Augie",
    "Augie",
    "August",
    "August Nights",
    "Augusta",
    "Auguste Eighth Month.",
    "Augustiko",
    "Augustin",
    "Augustina",
    "Augustine \"Gus\" Hoover",
    "Augustus",
    "Aunt Esther",
    "Aunt Jemima",
    "Aunt Kat",
    "Aunt Margaret",
    "Auntie Stella",
    "Aura",
    "Aureim",
    "Aureole",
    "Aurey",
    "Aurora",
    "Aurora Borealis",
    "Aussie",
    "Austin",
    "Austin Meowers",
    "Austin Powers",
    "Autobahn",
    "Autumn",
    "Ava",
    "Avagadros (after the mathmetician)",
    "Avail",
    "Avalanche",
    "Avalon",
    "Avanti",
    "Avatar",
    "Avery",
    "Avis",
    "Avocado",
    "Avril",
    "Awesie",
    "Awesome Kitty",
    "Awestruck",
    "Awk",
    "Axel",
    "Axl",
    "Axl Rose",
    "Axle",
    "Axon",
    "Ayame (Japanese for \"iris\")",
    "Ayesha (3rd wife of Mohammed)",
    "Ayisha",
    "Ayla",
    "Aylin",
    "Aymaya (Japanese for \"night rain\")",
    "Ayra",
    "Ayreh",
    "Ayun (As Yet Un-named)",
    "Azar",
    "Azark",
    "Azazel (means \"desert demon\", Bible: Leviticus)",
    "Azil",
    "Aziza (\"precious one\" in a few different languages)",
    "Azmodius",
    "Azour Mavreen",
    "Azrael",
    "Azreal",
    "Aztec",
    "Azure",
    "Azzuki",
    "Azzul",
    "B-52",
    "B-dee",
    "B-Girl",
    "B-Pal",
    "B.A.",
    "B.A. (Bad Attitude!)",
    "B.A. Barrakus",
    "B.B.",
    "B.B. Kat",
    "B.B. King",
    "B.B. Kingcat",
    "B.C.",
    "B.C. (\"Buttercup\")",
    "B.C. (Big Cat)",
    "B.D. (\"Black Douglas\", after the feisty Scottish warrior)",
    "B.D. (Bad Boy)",
    "B.D. (Brain-Dead)",
    "B.D.K. (\"Buddy D. Katt\")",
    "B.e.r.u. (Banana Emergency Recovery Unit, also Luke Skywalkers aunt and an island in the Pacific Ocean)",
    "B.G.",
    "B.I.F. (Butt In Face)",
    "B.J.",
    "B.J. (Tom Robbin's character Bonanza Jellybean)",
    "B.K.",
    "B.M.W. (Black, Mahogany & White)",
    "B.O.T. (Big Old Tom)",
    "B.u.d. (\"Big Ugly and Dumb\")",
    "B.W.",
    "B.W. (Black White)",
    "BA",
    "Ba Shaleek Alshain",
    "Ba' Boy",
    "Baba",
    "Babaganoush",
    "Babalou (after the tv show)",
    "Babar",
    "Babbaboombanorsh",
    "Babbit",
    "Babbitt",
    "Babe",
    "Babee",
    "Babers",
    "Babester",
    "Babette",
    "Babirusa",
    "Baboo",
    "Baboon Butt",
    "Babricus",
    "Babs (after Barbra Streisand)",
    "Babsy",
    "Babuji Braveheart",
    "Babur",
    "Babushka",
    "Baby",
    "Baby Bear",
    "Baby Beauty",
    "Baby Boogens",
    "Baby Boy",
    "Baby Bug",
    "Baby Butterscotch",
    "Baby Cakes",
    "Baby Cat",
    "Baby Doe (sort of a Jane Doe thang)",
    "Baby Dog",
    "Baby Doll",
    "Baby Doo II",
    "Baby Dumpling",
    "Baby Girl",
    "Baby Grey.",
    "Baby Guiness",
    "Baby Head",
    "Baby Jane",
    "Baby Jesus",
    "Baby Ki'n",
    "Baby Kitten",
    "Baby Kitty",
    "Baby Kitty And Trouble",
    "Baby Mimi",
    "Baby Nesbit",
    "Baby Ruth",
    "Baby Seebs",
    "Baby Spice",
    "Baby Weeeeeeezel the little Frrrrrench Chat",
    "Baby-Boogs",
    "Baby-Doll",
    "Baby-Doo",
    "Baby-Face",
    "Baby-Kitty",
    "Baby-Roca (named after two favorite candies, Baby Ruth and Almond Roca)",
    "Babycakes",
    "Babycat",
    "Babydoll",
    "Babyface",
    "Babygray",
    "Babykins",
    "Babyman",
    "Babyshoes",
    "Babytat",
    "Bacabs (Maya mythology: the canopic gods)",
    "Bacall",
    "Bacardi",
    "Baccarat",
    "Bacchos",
    "Bacchus",
    "Bacci (pronounced: Baa-chie; Italian for \"kisses\")",
    "Bach",
    "Baci",
    "Back",
    "Backstreet Blues",
    "Backstreet Kitty",
    "Bacon",
    "Bad Bad Boy",
    "Bad Bad Leroy Brown",
    "Bad Bess",
    "Bad Cat",
    "Bad Kitty",
    "Bad Luck",
    "Bada",
    "Badger",
    "Badjun",
    "Badlands",
    "Badness",
    "BadShad",
    "Baeki",
    "Bafftub",
    "Bag",
    "Bag Lady",
    "Bag O'Cat",
    "Bagel",
    "Baggage",
    "Baggi pants",
    "Baggins",
    "Baggy",
    "Bagheera",
    "Baghera (black panther in \"The Jungle Book\")",
    "Baghreeah",
    "Bagira",
    "Bagoas",
    "Bagpuss",
    "Baguette",
    "Bahama Mama",
    "Bailey",
    "Bailey Emerald Isle",
    "Bailey's Irish Cream (50% sweetness and 50% nuts)",
    "Bain",
    "Bainbridge",
    "Baja",
    "Bajan",
    "Baka (Japanese insult, \"idiot\", \"moron\", \"fool\", \"dimwit\")",
    "Baka-Neko",
    "Baker",
    "Baker (after the mountain in North Carolina, USA)",
    "Baksheesh (means \"bribe\" in Arabic)",
    "Balaena",
    "Balbina",
    "Balboa",
    "Balder (Viking mythology: The God of light)",
    "Balderdash",
    "Baldric",
    "Baldrick",
    "Baldur",
    "Baldur The Fairly Slow",
    "Baldwin",
    "Baldy",
    "Bali",
    "Balik",
    "Balin",
    "Balki",
    "Ballbearing Mouse Trap",
    "Ballerina",
    "Ballou",
    "Ballsy",
    "Baloo",
    "Balraj",
    "Balthazar",
    "Balzac",
    "Bam",
    "Bam-Bam",
    "Bama",
    "Bambalona",
    "Bambam",
    "Bambi",
    "Bambina",
    "Bambino",
    "Bamboo",
    "Bamboozler",
    "Bams",
    "Bamse",
    "Banana Cabana",
    "Banana Peel",
    "Band-Aid",
    "Bandanna",
    "Bandit",
    "Bandito",
    "Bang (reference to the Unix ! symbol)",
    "Bangladesh",
    "Bangle",
    "Bangui (capital of Central African Republic)",
    "Banjer",
    "Banjo",
    "Banjo Blue",
    "Bannana Fanna",
    "Bannenay",
    "Banner",
    "Banquet",
    "Banquo",
    "Banshee",
    "Banzai",
    "Bar Room",
    "Baracca",
    "Barbara",
    "Barbara Bush",
    "Barbarella (after the Jane Fonda movie)",
    "Barbarian",
    "Barbarino",
    "Barbeque",
]
